In [1]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
data = load_iris()

X = data.data
y = data.target

print("Sample Features:\n", X[:5])
print("\nSample Target:\n", y[:5])

Sample Features:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Sample Target:
 [0 0 0 0 0]


In [3]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
LOGISTIC REGRESSION

In [4]:
from sklearn.linear_model import LogisticRegression

baseline = LogisticRegression(max_iter=200)
baseline.fit(X_train, y_train)

y_pred_base = baseline.predict(X_test)

print("Baseline Accuracy (Logistic Regression):")
print(accuracy_score(y_test, y_pred_base))

Baseline Accuracy (Logistic Regression):
1.0


In [ ]:
Random Forest

In [5]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print("Random Forest Accuracy:")
print(accuracy_score(y_test, y_pred_rf))

Random Forest Accuracy:
1.0


In [ ]:
AdaBoost (Boosting)

In [6]:
from sklearn.ensemble import AdaBoostClassifier

ada = AdaBoostClassifier(n_estimators=50)
ada.fit(X_train, y_train)

y_pred_ada = ada.predict(X_test)

print("AdaBoost Accuracy:")
print(accuracy_score(y_test, y_pred_ada))

AdaBoost Accuracy:
1.0


In [ ]:
Gradient Boosting

In [7]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier()
gb.fit(X_train, y_train)

y_pred_gb = gb.predict(X_test)

print("Gradient Boosting Accuracy:")
print(accuracy_score(y_test, y_pred_gb))

Gradient Boosting Accuracy:
1.0
